name: kemet
description: "black consciousness design"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: 
  cupertino_icons: 
  firebase_core:   
  flutter:
    sdk: flutter
  flutter_dotenv: 
  flutter_markdown: 
  flutter_riverpod: 
  google_generative_ai: 
  hive_flutter: 
  http: 
  # flutter_cache_manager:
  google_fonts: 
  # flutter_svg:
  # flutter_staggered_grid_view:  
  logger: 
  flutter_staggered_animations:   

dev_dependencies:
  flutter_lints: 
  flutter_test:
    sdk: flutter
  mockito: 
  build_runner:
  flutter_launcher_icons:  

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
