// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp322ThahapQY4_MVqhfXyqA2VWS_1bqs',
    appId: '1:429993925523:web:e5ba5d64ebe81f719aa666',
    messagingSenderId: '429993925523',
    projectId: 'kemet-4d7bf',
    authDomain: 'kemet-4d7bf.firebaseapp.com',
    storageBucket: 'kemet-4d7bf.appspot.com',
    measurementId: 'G-GCS5YKX6CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyvbX8-GlgAvnIbQCAl4qgNBmiO8llO4s',
    appId: '1:429993925523:android:2218b892356795549aa666',
    messagingSenderId: '429993925523',
    projectId: 'kemet-4d7bf',
    storageBucket: 'kemet-4d7bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxLD1Jftt6Glm3wJx12GC2BwPqCvLW5Ko',
    appId: '1:429993925523:ios:7cb8cc404f0a8e8f9aa666',
    messagingSenderId: '429993925523',
    projectId: 'kemet-4d7bf',
    storageBucket: 'kemet-4d7bf.appspot.com',
    iosBundleId: 'com.example.kemet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxLD1Jftt6Glm3wJx12GC2BwPqCvLW5Ko',
    appId: '1:429993925523:ios:7cb8cc404f0a8e8f9aa666',
    messagingSenderId: '429993925523',
    projectId: 'kemet-4d7bf',
    storageBucket: 'kemet-4d7bf.appspot.com',
    iosBundleId: 'com.example.kemet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp322ThahapQY4_MVqhfXyqA2VWS_1bqs',
    appId: '1:429993925523:web:226ccfa8b5efee379aa666',
    messagingSenderId: '429993925523',
    projectId: 'kemet-4d7bf',
    authDomain: 'kemet-4d7bf.firebaseapp.com',
    storageBucket: 'kemet-4d7bf.appspot.com',
    measurementId: 'G-7KKNHXFLDL',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBp322ThahapQY4_MVqhfXyqA2VWS_1bqs',
    appId: '1:429993925523:web:e5ba5d64ebe81f719aa666',
    messagingSenderId: '429993925523',
    projectId: 'kemet-4d7bf',
    authDomain: 'kemet-4d7bf.firebaseapp.com',
    storageBucket: 'kemet-4d7bf.appspot.com',
    measurementId: 'G-GCS5YKX6CK',
  );
}